language: python
python:
    - "3.6"
services:
  - postgresql

env:
  global:
    - APP_SETTINGS=testing

install:
    - pip install -r requirements.txt

before_script:
  - "psql -c 'create database fastfoods_test;' -U postgres"

script:
    - py.test --cov

after_success:
- coveralls