language: python
python:
    - "3.6"
services:
  - postgresql
env:
  global:
    - APP_SETTINGS=testing
    - export JWT_SECRET_KEY=thisissecretkhahxcahiahiac
jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_USERNAME" --password-stdin
        - docker build -t travis-ci-demo .
        - docker tag travis-ci-demo $DOCKER_USERNAME/travis-ci-demo:1.0
        - docker push $DOCKER_USERNAME/travis-ci-demo
        - docker images




